# -*- coding: utf-8 -*-
"""Pair Trading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTLezLndLR1gKMWzqDjyx1PbXPU08WEh

1. 페어 선정 반도체 기업
"""

import itertools

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

from statsmodels.tsa.stattools import coint # 공적분

from statsmodels.tsa.stattools import adfuller # ADF 검정

#적은 샘플 반도체
tickers = [
    "NVDA",
    "AMD",
    "AVGO",
    "QCOM",
    "TXN",
    "ADI",
    "MU",
    "INTC",
    "AMAT",
    "LRCX",
]
train_start = '2015-01-01'
train_end = '2020-01-01'

data = yf.download(tickers, start=train_start, end=train_end, auto_adjust = True)
close = data['Close']
data.head()

close.head()

close.plot(figsize = (14, 6))
plt.show()

normalized_price = close / close.iloc[0] # 모든 시작을 1로 만들기
normalized_price.plot(figsize = (14, 6))
plt.show()               #같은 시작기준으로 만들어진 상승률 그래프

"""A. 상관관계"""

from logging import log
log_price = np.log(close) #로그가격
log_return = log_price.diff().dropna() #로그수익률
standard_return = close.pct_change().dropna()  #rets

correlation_matrix = close.corr() #로그 상관관계 matrix
correlation_matrix.round(2)

correlation_candidates = []
for ticker_a, ticker_b in  itertools.combinations(tickers, 2):

  corr = correlation_matrix.loc[ticker_a, ticker_b]

  if corr >= 0.5:
    correlation_candidates.append({
            "ticker_a": ticker_a,
            "ticker_b": ticker_b,
            "return_corr": corr,
        })
correlation_candidates = pd.DataFrame(correlation_candidates)

correlation_candidates = correlation_candidates.sort_values(
    "return_corr",
    ascending=False,
)

# corr .5 이상만 남기고 내림차순
# 상관관계는 결국 단기적인 움직임을 보여줌. 전체적인 경향성 흐름을 볼려면 공적분도 봐야함

correlation_candidates

"""B. Engle–Granger 공적분

p-val 이 작은 값 찾기
"""

cointegration_results = []
for _, row in correlation_candidates.iterrows():
  ticker_a = row["ticker_a"]
  ticker_b = row["ticker_b"]
  corr = row["return_corr"]

  # 두 종목의 공통 날짜만 남긴다.
  pair_price = log_price[[ticker_a, ticker_b]].dropna()

  # 관측치가 너무 적은 pair는 제외한다.
  if len(pair_price) < 500:
        continue

  # A를 종속변수, B를 설명변수로 Engle-Granger 검정
  score, p_value, _ = coint(
        pair_price[ticker_a],
        pair_price[ticker_b],
    )

  cointegration_results.append({
        "ticker_a": ticker_a,
        "ticker_b": ticker_b,
        "return_corr": row["return_corr"],
        "coint_pvalue": p_value,
    })

cointegration_results = pd.DataFrame(cointegration_results)

cointegration_results = cointegration_results.sort_values(
    "coint_pvalue"
)

cointegration_results

cointegrated_pairs = cointegration_results[
    cointegration_results["coint_pvalue"] < 0.05
].copy()

cointegrated_pairs

"""C. Hedge Ratio and Spread"""

best_pair = cointegrated_pairs.iloc[0]

ticker_a = best_pair["ticker_a"]
ticker_b = best_pair["ticker_b"]

pair_price = log_price[[ticker_a, ticker_b]].dropna()

beta, alpha = np.polyfit(     #find a, b in 회귀식
    pair_price[ticker_b],
    pair_price[ticker_a],
    1,
)

# epsil = y - alpha - beta * x
# 잔차 구하기
spread = (
    pair_price[ticker_a]
    - alpha
    - beta * pair_price[ticker_b]
)

spread.plot(figsize=(14, 5))

plt.axhline(
    spread.mean(),
    color="red",
    linestyle="--",
    label="Mean",
)

plt.title(f"Spread: {ticker_a} - {beta:.2f} × {ticker_b}")
plt.legend()
plt.show()

"""D. ADF 검정 -> spread의 정상성 확인

ADF 검정의 귀무가설  spread에 단위근이 있어 비정상적이다
"""

adf_result = adfuller(
    spread,

    # AIC로 사용할 lag 수를 자동 선택 lag = 과거 어느 시점까지 사용할 것인지
    autolag="AIC",
)

adf_statistic = adf_result[0]
adf_pvalue = adf_result[1]

print("ADF statistic:", adf_statistic) # adf 검정통계량
print("ADF p-value:", adf_pvalue) # pval

if adf_pvalue < 0.05:
    print("spread가 정상적이라는 증거가 있음")
else:
    print("spread가 정상적이라고 보기 어려움")

"""E. 평균회귀 반감기 계산

"""

# 전날 spread
lagged_spread = spread.shift(1)

# 오늘 spread와 전날 spread의 변화량
spread_change = spread.diff()

half_life_data = pd.DataFrame({
    "spread_change": spread_change,
    "lagged_spread": lagged_spread,
}).dropna()

b, intercept = np.polyfit(
    half_life_data["lagged_spread"],
    half_life_data["spread_change"],
    1,
)

print("Mean-reversion coefficient:", b) #회귀계수 b

if b < 0:
    half_life = -np.log(2) / b
else:
    # b가 양수라면 평균으로 돌아가기보다 벌어지는 관계
    half_life = np.inf

print("Half-life:", half_life, "trading days")

def analyze_pair(
    log_price,
    ticker_a,
    ticker_b,
    min_observations=500,
):
    """
    두 종목의 공적분 관계와 평균회귀 특성을 계산한다.

    Parameters
    ----------
    log_price : DataFrame
        종목별 로그가격
    ticker_a, ticker_b : str
        검사할 두 종목
    min_observations : int
        필요한 최소 공통 관측치

    Returns
    -------
    dict 또는 None
        pair의 통계량. 데이터가 부족하면 None.
    """

    # 두 종목 모두 가격이 존재하는 날짜만 선택
    pair = log_price[[ticker_a, ticker_b]].dropna()

    if len(pair) < min_observations:
        return None

    y = pair[ticker_a]
    x = pair[ticker_b]

    # 1. Engle-Granger 공적분 검정
    _, coint_pvalue, _ = coint(y, x)

    # 2. y = alpha + beta*x 회귀
    beta, alpha = np.polyfit(x, y, 1)

    # 3. 회귀 잔차를 spread로 정의
    spread = y - alpha - beta * x

    # 4. spread의 ADF 검정
    adf_pvalue = adfuller(
        spread,
        autolag="AIC",
    )[1]

    # 5. 반감기 계산
    half_life_data = pd.DataFrame({
        "spread_change": spread.diff(),
        "lagged_spread": spread.shift(1),
    }).dropna()

    reversion_coefficient, _ = np.polyfit(
        half_life_data["lagged_spread"],
        half_life_data["spread_change"],
        1,
    )

    if reversion_coefficient < 0:
        half_life = -np.log(2) / reversion_coefficient
    else:
        half_life = np.inf

    return {
        "ticker_a": ticker_a,
        "ticker_b": ticker_b,
        "n_observations": len(pair),
        "coint_pvalue": coint_pvalue,
        "adf_pvalue": adf_pvalue,
        "alpha": alpha,
        "hedge_ratio": beta,
        "half_life": half_life,
    }

analyze_pair(
    log_price,
    "AMD",
    "NVDA",
)

"""Finish"""

all_results = []

for _, row in correlation_candidates.iterrows():

    result = analyze_pair(
        log_price=log_price,
        ticker_a=row["ticker_a"],
        ticker_b=row["ticker_b"],
    )

    if result is None:
        continue

    # 앞에서 계산한 상관계수도 결과에 추가
    result["return_corr"] = row["return_corr"]

    all_results.append(result)

results = pd.DataFrame(all_results)

results.head()



selected_pairs = results[
    # 공적분 관계
    (results["coint_pvalue"] < 0.05)

    # 직접 만든 spread도 정상적이어야 함
    & (results["adf_pvalue"] < 0.05)

    # hedge ratio가 음수인 특이한 조합 제외
    & (results["hedge_ratio"] > 0)

    # 너무 빠르거나 너무 느린 평균회귀 제외
    & (results["half_life"].between(2, 60))
].copy()


selected_pairs = selected_pairs.sort_values(
    by=[
        "coint_pvalue",
        "half_life",
    ],
    ascending=[
        True,
        True,
    ],
)

selected_pairs

selected_pairs.to_csv(
    "selected_pairs.csv",
    index=False,
)

